export default {
  paginationEl: document.getElementById('pagination'),
  header: document.querySelector('header'),
  btnBox: document.querySelector('.buttons-box'),
  searchForm: document.querySelector('.header-form'),
  homeLink: document.getElementById('home'),
  libraryLink: document.getElementById('library'),
  list: document.querySelector('#card-set-js'),
  input: document.querySelector('#search-input'),
  notifyEr: document.querySelector('#input-error'),
  dinamicButtons: document.getElementById('dinamic-buttons-js'),
  searchHeadIcon: document.querySelector('.search__icon'),
  buttonScrollToUp: document.querySelector('#btn-scroll-up'),
  teamModal: document.querySelector('#team'),
  btnCloseModal: document.querySelector('.developers__button'),
  body: document.querySelector('body'),
  switch: document.querySelector('.theme-switch__toggle'),
  watchedButton : document.getElementById('watched'),
  queueButton : document.getElementById('queue'),
  spinerContainer: document.querySelector('.spiner-js'),
};
