export default {
  paginationEl: document.getElementById('pagination'),
  header: document.querySelector('header'),
  btnBox: document.querySelector('.buttons-box'),
  searchForm: document.querySelector('.header-form'),
  homeLink: document.getElementById('home'),
  libraryLink: document.getElementById('library'),
  list: document.querySelector('#card-set-js'),
  input: document.querySelector('#search-input'),
  notifyEr: document.querySelector('#input-error'),
  dinamicButtons: document.getElementById('dinamic-buttons-js'),
  libraryLink: document.getElementById('library'),
  header: document.querySelector('header'),
  btnBox: document.querySelector('.buttons-box'),
  searchForm: document.querySelector('.header-form'),
  homeLink: document.getElementById('home'),
};
