import './sass/main.scss';
import './js/header-logic';
import './js/library';
import './js/main-page';
import './js/pagination';
import './js/featch-movie';
import './js/modal-window';
import './js/scroll-top';
import './js/loader';
